---

- ignore:
    name: Use head

- flags:
    - default: true
    - name:
        - "-fdefer-typed-holes"
        - "-Wno-typed-holes"
      within: []

- modules:
  - name: Data.ByteString
    as: BS
  - name: Data.ByteString.Lazy
    as: BSL
