name: bitcoin
version: 0.1.0
synopsis: Bitcoin library for Haskell
description: Please see the README on GitHub at <https://github.com/haskell-bitcoin/bitcoin#readme>
category: Bitcoin, Finance, Network
author:
  - Philippe Laprade
  - Jean-Pierre Rupp
  - Matthew Wraith
  - Keagan McClelland
maintainer: keagan.mcclelland@gmail.com
license: BSD3
license-file: LICENSE
homepage: http://github.com/haskell-bitcoin/bitcoin#readme
git: git://github.com/haskell-bitcoin/bitcoin.git
bug-reports: http://github.com/haskell-bitcoin/bitcoin/issues
extra-source-files:
  - data/*.json
  - README.md
  - CHANGELOG.md
dependencies:
  - array >= 0.5.4.0
  - base >=4.9 && <5
  - base16 >= 0.3.0.1
  - binary >= 0.8.8
  - bytes >= 0.17
  - bytestring >= 0.10.10.0
  - cereal >= 0.5.8
  - containers >= 0.6.2.1
  - cryptonite >= 0.26
  - deepseq >= 1.4.4.0
  - entropy >= 0.4.1.5
  - hashable >= 1.3.0.0
  - hspec >= 2.7.1
  - memory >= 0.15.0
  - murmur3 >= 1.0.3
  - network >= 3.1.1.1
  - QuickCheck >= 2.13.2
  - split >= 0.2.3.3
  - safe >= 0.3.18
  - scientific >= 0.3.6.2
  - secp256k1-haskell >= 0.4.0
  - string-conversions >= 0.4.0.1
  - text >= 1.2.3.0
  - time >= 1.9.3
  - transformers >= 0.5.6.2
  - unordered-containers >= 0.2.10.0
  - vector >= 0.12.1.2
library:
  source-dirs: src
  other-modules: Bitcoin.Keys.Extended.Internal
  when:
    - condition: false
      other-modules: Paths_bitcoin
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
    dependencies:
      - aeson >= 1.4.6.0
      - base64 ^>= 0.4
      - bitcoin
      - hspec >= 2.7.1
      - HUnit >= 1.6.0.0
      - QuickCheck >= 2.13.2
      - lens-aeson >= 1.1
      - lens >= 4.18.1
