resolver: lts-19.27
system-ghc: true
nix:
  packages:
    - secp256k1
    - pkg-config
extra-deps:
  - fourmolu-0.8.2.0
  - cryptonite-0.30
  - github: tochicool/libsecp256k1-haskell
    commit: 3a23ec0d8616bd3cc45e3b5764f604c4bed2e144
