resolver: lts-22.6
system-ghc: true
nix:
  packages:
    - secp256k1
    - pkg-config
extra-deps:
  - fourmolu-0.8.2.0
  - cryptonite-0.30
  - secp256k1-haskell-0.7.0
packages:
  - ./bitcoin
  - ./bitcoin-test
  - ./bitcoin-bench
