resolver: lts-19.27
system-ghc: true
nix:
  packages:
    - secp256k1
    - pkg-config
extra-deps:
  - fourmolu-0.8.2.0
  - cryptonite-0.30
  - github: tochicool/libsecp256k1-haskell
    commit: 2688e0b86dbbc81a9eb117af3f3a078c84e1c2ef
