resolver: lts-22.6
system-ghc: false
nix:
  packages:
    - pkg-config
extra-deps:
  - cryptonite-0.30
  - libsecp256k1-0.2.1
  # for fourmolu CI
  - fourmolu-0.14.0.0
  - ghc-lib-parser-9.6.2.20230523
packages:
  - ./bitcoin
  - ./bitcoin-test
  - ./bitcoin-bench
