name: bitcoin
version: 0.1.0
synopsis: Bitcoin library for Haskell
description: Please see the README on GitHub at <https://github.com/haskell-bitcoin/bitcoin#readme>
category: Bitcoin, Finance, Network
author:
  - Philippe Laprade
  - Jean-Pierre Rupp
  - Matthew Wraith
  - Keagan McClelland
maintainer: keagan.mcclelland@gmail.com
license: BSD3
license-file: LICENSE
homepage: http://github.com/haskell-bitcoin/bitcoin#readme
git: git://github.com/haskell-bitcoin/bitcoin.git
bug-reports: http://github.com/haskell-bitcoin/bitcoin/issues
dependencies:
  - array >= 0.5.4.0
  - base >=4.9 && <5
  - base16 >= 1
  - binary >= 0.8.8
  - bytestring >= 0.10.10.0
  - containers >= 0.6.2.1
  - cryptonite >= 0.30
  - deepseq >= 1.4.4.0
  - hashable >= 1.3.0.0
  - memory >= 0.15.0
  - murmur3 >= 1.0.3
  - network >= 3.1.1.1
  - split >= 0.2.3.3
  - secp256k1-haskell >= 0.4.0 && < 1
  - string-conversions >= 0.4.0.1
  - text >= 1.2.3.0
  - transformers >= 0.5.6.2
  - unordered-containers >= 0.2.10.0
  - vector >= 0.12.1.2
library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_bitcoin
