name: Fourmolu

concurrency:
  group: ${{ github.ref }}-fourmolu
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths:
      - fourmolu.yaml
      - "**/*.hs"
      - ".github/workflows/fourmolu.yaml"
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review
  push:
    branches:
      - master
    paths:
      - fourmolu.yaml
      - "**/*.hs"
      - ".github/workflows/fourmolu.yaml"
  workflow_dispatch:
    inputs: {}

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        name: Checkout
      - uses: haskell-actions/run-fourmolu@5a9f41fa092841e52e6c57dde5600e586fa766a4
        name: Run fourmolu
        with:
          version: "0.8.2.0"
